namespace MauiApp1;

public partial class NewPage1 : ContentPage
{
	// Example: this is the code-behind file for the NewPage1.xaml file
	// I didnt fill it out because I didnt want to type out all the code
	// see my example in TestPage.cs
	public NewPage1()
	{
		//this is the constructor
		//this is where we initialize the page
		//this is where we create and initialize the controls
		//this is where we set the properties of the controls
		//this is where we setup the layout of the controls
		//this is where we add the controls to the page
		//this is where we set the content of the page
		//all of this is auto-generated by the IDE from the xaml file
		//InitializeComponent() is a method that is auto-generated by the IDE
		//it is used to initialize the page
		InitializeComponent();
	}
}